language: php

os:
  - linux
  - osx

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - make install-dev

script:
  - make testdox

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
