language: php

os:
  - linux
  - osx

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer selfupdate --quiet
  - COMPOSER_PROCESS_TIMEOUT=10000 composer install
  - ./vendor/bin/phing rw

script:
  - ./vendor/bin/phing test -verbose

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
